[[collection]]
type = "box"
title = "EU approach to Artificial Intelligence"
subtitle = "2023, 2024, 2025, 2026" # optional
#link = "https://example.com" # optional
#img = "https://example.com/image.png" # optional


[[collection]]
type = "box"
title = "Trustworthy Artificial Intelligence"
subtitle = "2022, 2023, 2024, 2025" # optional
#link = "https://example.com" # optional
#img = "https://example.com/image.png" # optional

[[collection]]
type = "box"
title = "How do social media platforms allow users to consume content?"
subtitle = "2024, 2025" # optional
#link = "https://example.com" # optional
#img = "https://example.com/image.png" # optional

[[collection]]
type = "box"
title = "AI ethics and misinformation"
subtitle = "2024" # optional
#link = "https://example.com" # optional
#img = "https://example.com/image.png" # optional